version: '3.3'

services: 
    backend:
        build: backend
        container_name: backend
        restart: unless-stopped
        working_dir: /backend
        volumes:
            - ./backend:/backend
        command: pipenv run python manage.py runserver 0.0.0.0:9000
        expose:
            - 9000
        networks:
            - back-tier

    db:
        image: postgres
        restart: unless-stopped
        container_name: db
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        expose:
            - 5432
        networks:
            - back-tier
            
    frontend:
        build: frontend
        container_name: frontend
        restart: unless-stopped
        working_dir: /frontend
        volumes:
            - ./frontend:/frontend
        command: npm run start
        expose:
            - 3000
        networks:
            - front-tire
    proxy:
        image: nginx:stable-alpine
        restart: unless-stopped
        container_name: proxy
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "443:443"
            - "9000:9000"
            - "3000:3000"
        networks:
            - back-tier
            - front-tire

networks:
    front-tire: {}
    back-tier: {}
